/**
 * Author: Kham Nguyen
 * content: constants for details user
 * Date created: 23-June-2018
 * Date modified: 23-June-2018
 * Last modify by: Kham Nguyen
 */
export const types = {
    GET_DATA_BY_ID_SUCCESS: 'GET_DATA_BY_ID_SUCCESS',
    UPDATE_ACTIVE_KEY: 'UPDATE_ACTIVE_KEY',
    GET_ALBUMS_BY_USER_ID_SUCCESS: 'GET_ALBUMS_BY_USER_ID_SUCCESS',
    GET_POSTS_BY_USER_ID_SUCCESS: 'GET_POSTS_BY_USER_ID_SUCCESS',
    UPDATE_SHOW_POST: 'UPDATE_SHOW_POST',
    POST_SELECTED: 'POST_SELECTED',
    GET_COMMENTS_BY_POST_SUCCESS: 'GET_COMMENTS_BY_POST_SUCCESS',
    ALBUM_SELECTED: 'ALBUM_SELECTED',
    UPDATE_SHOW_ALBUM: 'UPDATE_SHOW_ALBUM',
    GET_PHOTOS_BY_ALBUM_ID_SUCCESS: 'GET_PHOTOS_BY_ALBUM_ID_SUCCESS',
    SHOW_FULL_SIZE_IMAGE: 'SHOW_FULL_SIZE_IMAGE',
    SHOW_EDIT_POST: 'SHOW_EDIT_POST',
    POST_SELECTED_TO_EDIT: 'POST_SELECTED_TO_EDIT',
    SHOW_DELETE_POST: 'SHOW_DELETE_POST',
    POST_SELECTED_TO_DELETE: 'POST_SELECTED_TO_DELETE',
    SHOW_ADD_POST: 'SHOW_ADD_POST',
};
